name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: "test"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Lint
        shell: bash
        run: poetry run flake8

      - name: Test
        shell: bash
        run: poetry run pytest
