name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.7

      - name: Install poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Create requirements.txt
        shell: bash
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: Deploy to dev environment
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          push_arguments: "-f manifest-dev.yml nad-ch-dev"
