name: Deploy Dev

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Install poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install frontend dependencies and build assets
        run: |
          cd nad_ch/controllers/web
          npm install
          npm run build

      - name: Create requirements.txt
        shell: bash
        run: poetry export --without-hashes --format=requirements.txt > requirements.txt

      - name: Deploy to dev environment
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          push_arguments: "-f manifest-dev.yml 10x-nad-ch-dev"
